### PR TITLE
updating design doc with new user stories

### PR DESCRIPTION
**Pull request by cranders-bio**
Took a stab at some updated user stories and component descriptions. Still pretty bare bones but wanted to let you all know what was in my head. Let me know if this sounds reasonable to you all!

### CODE REVIEW

**Comment by jthomson-apluw** [comment]
Is this part of the class project with @jacobrdavis and @edwinrainville ?

**Comment by cranders-bio** [comment]
@jthomson-apluw Yes! I am in CSE 583 with @jacobrdavis and @edwinrainville. My apologies if this pull request blasted a notification to all of the watchers.

**Comment by jthomson-apluw** [comment]
No apology needed-- glad to have help cleaning, organizing, and improving-- just keeping track of who/what is going on in our org.

**Review by jacobrdavis — APPROVED** [review]
This is awesome. Thank you, Chris. Will pop back in here soon to populate the Developer use-case.

**Pull request merged**
